"""Render the public project catalog from reviewed repository facts."""
from pathlib import Path
import html, json, shutil

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'site'
OUT.mkdir(exist_ok=True)
E = html.escape
projects = [
 dict(slug='athena-skill', name='ATHENA', category='Agent workflows', tag='Skill + CLI', pitch='Keep an audit trail from a request to shipped code.', use='Use an AI coding agent on a project that needs recorded decisions, requirements, tasks, and execution evidence.', requirements='Codex or Claude Code, Python 3, Git.', commands='git clone https://github.com/taylorparsons/athena-skill.git\ncd athena-skill\ncp -r skills/athena ~/.claude/skills/', steps=['Install the packaged skills/athena directory in your agent skill directory. Codex installation is documented in the source README.', 'Restart the agent and ask it to set up ATHENA docs in your project.', 'Open sessions with ./scripts/owl context. Capture requests, specify a feature, execute tasks, and record evidence through Owl.', 'Use ./scripts/owl show <ID> or ./scripts/owl why <FR-ID> to inspect a decision or requirement chain.'], flow=['Request + decision','Spec + task','Code + evidence'], detail='Owl is the deterministic gateway for context and audit records. The optional Owl agent and hooks are documented for Claude Code. Codex uses the CLI.', docs=['skills/athena/SKILL.md','docs/TRACEABILITY.md'], image='https://raw.githubusercontent.com/taylorparsons/athena-skill/main/docs/images/athena-readme-fast-visual.svg'),
 dict(slug='interview-practice-app', name='Interview Practice', category='Generative AI', tag='FastAPI + voice', pitch='Practice interviews against your resume and a job description.', use='Prepare for a specific role, rehearse spoken answers, and review generated feedback and example answers.', requirements='Python 3.9+, pip, and an OpenAI API key for voice. A browser microphone is needed for spoken sessions.', commands='git clone https://github.com/taylorparsons/interview-practice-app.git\ncd interview-practice-app\ncp env.example .env\n# Add OPENAI_API_KEY to .env\nchmod +x run_voice.sh\n./run_voice.sh', steps=['Upload your resume and upload or paste the job description.', 'Generate questions and type answers to receive content and tone feedback.', 'Start Voice Session and allow microphone access to rehearse with the realtime coach.', 'Resume an autosaved session, or export the transcript. PDF export requires the system libraries listed in the README.'], flow=['Resume + role','Question + answer','Feedback + practice'], detail='FastAPI handles question generation and evaluation. Voice coaching uses OpenAI Realtime over WebRTC. Session data is saved on the server and the session ID in the browser.', docs=['docs/2025-11-26-evaluation-schema-enforcement.md','docs/DEMO_STAGE_VOICE_SETTINGS.md'], image='https://github.com/user-attachments/assets/cb113ba3-24b8-43dd-86db-2b01f6e00915'),
 dict(slug='cortege-hackathon', name='CORTEGE', category='Generative AI', tag='Hackathon prototype', pitch='Explore household-aware fraud assessment with companion agents.', use='Demonstrate a household fraud case using a simulated event or phone call plus a message excerpt, suspicious URL, or screenshot note.', requirements='Node.js 18+, npm, and an Anthropic API key. Twilio integration requires the separate deployment setup.', commands='git clone https://github.com/taylorparsons/cortege-hackathon.git\ncd cortege-hackathon\n./run-local.sh\n# Add ANTHROPIC_API_KEY when prompted', steps=['Open the frontend at http://localhost:5173. The backend runs on port 3001.', 'Choose or create a household and select its members.', 'Use the event simulator or Live Feed to add a test event and a manual evidence item.', 'Review the generated case severity, signals, rationale, and recommended action. Stop the app with ./stop-local.sh.'], flow=['Event + evidence','Household agents','Explainable risk case'], detail='The React frontend connects to an Express backend through REST and WebSocket. An orchestrator manages member-specific agents and Claude assessments. This is a prototype with heuristics, not verified fraud prevention or image/video authenticity detection.', docs=['docs/API.md','docs/PRODUCTION_DEPLOYMENT.md']),
 dict(slug='talk-to-me', name='Piper TTS Reader', category='Local tools', tag='Rust + local speech', pitch='Read text aloud on macOS with local Piper voice models.', use='Listen to articles, drafts, or selected browser text while following sentence highlighting. Synthesis uses the local Piper CLI.', requirements='macOS, Rust, the Piper CLI, and a Piper voice model. setup.sh assists with dependencies and downloads.', commands='git clone https://github.com/taylorparsons/talk-to-me.git\ncd talk-to-me\n./setup.sh\n./target/release/piper-tts-reader', steps=['Paste text into the app and choose an installed voice.', 'Set the speech speed and press Play. Follow the highlighted sentences; press Stop to halt playback.', 'For Chrome, load chrome-extension/ through chrome://extensions with Developer mode enabled.', 'Keep the desktop app running, select browser text, and choose Read with Piper. Optional login startup uses ./install-agent.sh.'], flow=['Text selection','Local Piper model','Audio + highlighting'], detail='The Rust GUI shells out to Piper rather than embedding ONNX. The Chrome extension sends selected text to the app at 127.0.0.1:7845. Models live in ~/.local/share/piper-reader/models/.', docs=[]),
 dict(slug='pptx_extractor', name='PPTX Utility', category='Local tools', tag='Python + Streamlit', pitch='Extract presentation content to JSON, edit it, and recreate a deck.', use='Make repeatable text changes to PowerPoint files or prepare structured presentation content for an AI-assisted editing workflow.', requirements='Python 3.x and the repository dependencies. run.sh creates a virtual environment and installs dependencies.', commands='git clone https://github.com/taylorparsons/pptx_extractor.git\ncd pptx_extractor\nchmod +x run.sh\n./run.sh ui', steps=['Use the Extract tab to select a PPTX and an output directory.', 'Edit the generated *_info.json file, then validate it in Validate / Filter JSON.', 'Provide the original presentation as the template in Recreate to retain its styling and supported SmartArt.', 'Open the recreated PPTX and inspect the slides. CLI: ./run.sh <pptx_path> <output_dir> --extract or --recreate.'], flow=['Original PPTX','Editable JSON','Recreated PPTX'], detail='The tool extracts and recreates presentation structures. It does not itself require an LLM. Preserve the original file and inspect the recreated deck before using it.', docs=[] , image='https://raw.githubusercontent.com/taylorparsons/pptx_extractor/main/assets/readme-banner.svg'),
 dict(slug='linux-mint-headless-setup', name='Headless Linux Setup', category='Agent workflows', tag='Skill + runbooks', pitch='Repurpose a Windows PC or Intel iMac as a Linux Mint server.', use='Guide an agent through hardware assessment, Linux installation, and headless administration with SSH, Docker, and file sharing.', requirements='A Windows PC or Intel iMac, Linux Mint installation media, and an agent that can read SKILL.md. Installation choices depend on the hardware and disk layout.', commands='git clone https://github.com/taylorparsons/linux-mint-headless-setup.git\ncd linux-mint-headless-setup\ncp -r skills/headless-linux-server ~/.claude/skills/', steps=['Describe your hardware and whether you want dual boot or a Linux-only installation to the agent.', 'Let the skill choose the Windows BIOS or iMac EFI reference. Review the disk layout and preserve backups before partition changes.', 'Follow the platform-specific installation runbook.', 'Use the post-install reference for SSH, Docker, Caddy, Samba, and VNC over an SSH tunnel. Adapt the server admin scripts to your own machine.'], flow=['Hardware assessment','Platform runbook','Headless server'], detail='The reusable skill loads only the reference needed for the hardware. The repository also contains administration scripts from a ThinkPad deployment; machine-specific settings are examples to adapt.', docs=['skills/headless-linux-server/SKILL.md','skills/headless-linux-server/references/post-install.md']),
 dict(slug='wa-state-ferry-tracker', name='Washington Ferry Tracker', category='Web tools', tag='Map + public data', pitch='Explore ferry locations, terminal cameras, and queue estimates.', use='Check Puget Sound ferry activity and terminal conditions. Enable WSDOT polling to replace the default simulation data.', requirements='A browser. For local use, Python 3.9+ or Docker. A WSDOT access code is needed for direct live polling.', commands='git clone https://github.com/taylorparsons/wa-state-ferry-tracker.git\ncd wa-state-ferry-tracker\npython3 -m http.server 8001', steps=['Open http://localhost:8001 or the application linked in the source README.', 'Explore the map, route filters, terminal cameras, and queue predictor.', 'Request an access code through the WSDOT Traveler Information API portal.', 'Use WSDOT API in the navigation to save your code and enable direct polling. The code is stored in browser localStorage.'], flow=['WSDOT data','Map + queue model','Trip planning'], detail='The frontend uses Leaflet with map tiles, browser view persistence, and a theme switcher. Queue results are estimates. Without direct polling configured, telemetry is simulated.', docs=[]),
 dict(slug='git_helper', name='Git Helper', category='Local tools', tag='Reference + diagram', pitch='Understand Git commands and the workflow around them.', use='Look up a command, understand when to use it, and check the result before taking the next step.', requirements='Git to clone the repository. PlantUML is optional for rendering the workflow diagram.', commands='git clone https://github.com/taylorparsons/git_helper.git\ncd git_helper\ncat README.md', steps=['Read the README for the Git troubleshooting examples that are present.', 'Use git status to inspect the current state before making changes.', 'The README mentions git_commands.md and git_seq.puml, but both files are absent from the current main branch. There is no diagram to render in this checkout.', 'Check the repository for updates before relying on the larger command guide.'], flow=['Inspect state','Choose command','Verify result'], detail='Current main contains README.md and LICENSE only. The intended command guide and PlantUML diagram described in the README have not been published there. Treat this as a README reference with missing companion files.', docs=[]),
]

def nav(prefix=''):
 return f'<header><a class="brand" href="{prefix}index.html">TP<span> / Open source</span></a><nav aria-label="Main"><a href="{prefix}index.html#projects">Projects</a><a href="{prefix}use-cases.html">Use cases</a><a href="{prefix}about.html">About</a><a href="https://github.com/taylorparsons">GitHub ↗</a></nav></header>'
def page(title, body, prefix=''):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Taylor Parsons</title><meta name="description" content="Open source tools and agent workflows by Taylor Parsons. Use cases, setup, and technical guides."><meta property="og:image" content="https://taylorparsons.github.io/assets/images/og.svg"><link rel="icon" href="{prefix}assets/images/favicon.svg"><link rel="stylesheet" href="{prefix}assets/styles.css"></head><body><a class="skip" href="#main">Skip to content</a>{nav(prefix)}<main id="main">{body}</main><footer><p>Taylor Parsons / Build, inspect, iterate.</p><p>Guides reviewed against public repository documentation on October 4, 2026.</p><a href="https://github.com/taylorparsons/taylorparsons.github.io">Site source ↗</a></footer><script src="{prefix}assets/main.js"></script></body></html>'''
def flow(labels):
 return '<ol class="flow" aria-label="Workflow">'+''.join(f'<li><span>0{i+1}</span>{E(label)}</li>' for i,label in enumerate(labels))+'</ol>'
def card(p):
 return f'<article class="card" data-category="{E(p["category"])}" data-search="{E(p["name"]+" "+p["pitch"]+" "+p["category"])}"><p class="eyebrow">{E(p["category"])} / {E(p["tag"])}</p><h3><a href="projects/{p["slug"]}.html">{E(p["name"])}</a></h3><p>{E(p["pitch"])}</p><a class="text-link" href="projects/{p["slug"]}.html">Use cases & setup <span aria-hidden="true">↗</span></a></article>'

hero='<section class="hero"><div><p class="eyebrow">Taylor Parsons / Project field guide</p><h1>Build with AI.<br><span>Keep your hands<br>on the tools.</span></h1><p class="lead">Open source projects for technologists working with generative AI, agent workflows, local speech, and the systems around them.</p><a class="button" href="#projects">Explore the projects ↓</a></div><div class="blueprint"><p class="eyebrow">From intent to something you can run</p><div class="orbit"><span class="node n1">CONTEXT</span><span class="node n2">WORKFLOW</span><span class="node n3">EXECUTION</span><span class="node n4">EVIDENCE</span><div class="core">BUILD<br><span>↻ ITERATE</span></div></div><p>Give the agent context. Run the workflow.<br>Inspect the result. Repeat.</p></div></section>'
body=hero+'<section class="intro"><p class="eyebrow">Eight public projects</p><h2>A starting point for your next build.</h2><p>Choose a problem, read the workflow, then follow the setup guide. AI applications sit alongside local utilities, reusable skills, and reference tools.</p></section><section id="projects"><div class="catalog-head"><h2>Project catalog</h2><label>Find a project<input id="search" type="search" placeholder="Search projects or use cases"></label></div><div class="filters" aria-label="Project categories"><button class="active" data-filter="all" aria-pressed="true">All projects</button>'+''.join(f'<button data-filter="{x}" aria-pressed="false">{x}</button>' for x in ['Generative AI','Agent workflows','Local tools','Web tools'])+'</div><p id="results" class="small" aria-live="polite">8 projects</p><div class="grid">'+''.join(card(p) for p in projects)+'</div></section>'
(OUT/'index.html').write_text(page('Open source for hands-on technologists',body))
(OUT/'projects').mkdir(exist_ok=True)
for p in projects:
 repo='https://github.com/taylorparsons/'+p['slug']
 docs=''.join(f'<li><a href="{repo}/blob/main/{d}">{E(d)}</a></li>' for d in ['README.md']+p['docs'])
 image=f'<figure><img loading="lazy" src="{p["image"]}" alt="{E(p["name"])} repository visual"><figcaption>Visual from the public repository.</figcaption></figure>' if p.get('image') else ''
 body=f'<p class="breadcrumb"><a href="../index.html#projects">Projects</a> / {E(p["name"])}</p><section class="project-hero"><p class="eyebrow">{E(p["category"])} / {E(p["tag"])}</p><h1>{E(p["name"])}</h1><p class="lead">{E(p["pitch"])}</p><a class="button" href="{repo}">View source ↗</a><a class="button secondary" href="#setup">Try it ↓</a></section>{flow(p["flow"])}<div class="article-layout"><aside><p class="eyebrow">On this page</p><a href="#use-case">Use case</a><a href="#setup">Get started</a><a href="#usage">How to use</a><a href="#details">Technical details</a><a href="#docs">Source documentation</a></aside><article class="prose"><section id="use-case"><h2>When to use it</h2><p>{E(p["use"])}</p></section><section id="setup"><h2>Get started</h2><h3>Requirements</h3><p>{E(p["requirements"])}</p><div class="code-head"><span>Terminal</span><button class="copy">Copy commands</button></div><pre><code>{E(p["commands"])}</code></pre></section><section id="usage"><h2>How to use</h2><ol>'+''.join(f'<li>{E(s)}</li>' for s in p['steps'])+f'</ol></section><section id="details"><h2>Under the hood</h2><p>{E(p["detail"])}</p>{image}</section><section id="docs"><h2>Source documentation</h2><ul>{docs}</ul><p>Setup instructions are taken from the public repository. Dependencies, API availability, and scripts can change; check the source README for updates.</p><a href="{repo}/issues">Questions or issues ↗</a></section></article></div><section class="next"><h2>Explore another workflow</h2><a href="../use-cases.html">Browse by use case ↗</a></section>'
 (OUT/'projects'/f'{p["slug"]}.html').write_text(page(p['name'],body,'../'))
cases=[('Build with a coding agent','Capture intent, record decisions, and follow implementation evidence.',['athena-skill']),('Prepare for a role','Use a resume and job description as context for generated questions and spoken practice.',['interview-practice-app']),('Prototype companion agents','Explore event ingestion, household context, and an explainable risk case.',['cortege-hackathon']),('Keep speech synthesis local','Read selected text using models running on your Mac.',['talk-to-me']),('Edit presentations through structured data','Extract a deck, revise JSON content, validate it, and recreate the slides.',['pptx_extractor']),('Repurpose hardware','Use a platform-aware skill to guide Linux installation and server setup.',['linux-mint-headless-setup']),('Work with maps and public data','Explore a browser frontend for ferry positions and terminal conditions.',['wa-state-ferry-tracker']),('Understand the Git workflow','Use command references and sequence diagrams to check each step.',['git_helper'])]
body='<section class="project-hero"><p class="eyebrow">Start with the problem</p><h1>Use cases</h1><p class="lead">Find the project that fits the work in front of you.</p></section><div class="grid">'
for title,desc,slugs in cases:
 body+=f'<article class="card"><h2>{E(title)}</h2><p>{E(desc)}</p>'+''.join(f'<a href="projects/{s}.html">{E(next(p["name"] for p in projects if p["slug"]==s))} ↗</a>' for s in slugs)+'</article>'
(OUT/'use-cases.html').write_text(page('Use cases',body+'</div>'))
(OUT/'about.html').write_text(page('About','<section class="project-hero"><p class="eyebrow">Taylor Parsons</p><h1>Back to the tools.</h1><p class="lead">I build software, explore AI workflows, and share the parts other technologists can use.</p></section><article class="prose about"><h2>What this site covers</h2><p>This catalog brings together eight public projects: generative AI applications, coding-agent skills, local utilities, and web tools. Each guide explains the use case, requirements, workflow, and how to run it.</p><h2>Working from source</h2><p>The repository is the source of truth for each project. These pages help you find a starting point. Check its README and license before adopting code, and use the project issue tracker for questions.</p><h2>Connect</h2><p><a href="https://github.com/taylorparsons">Taylor Parsons on GitHub ↗</a></p></article>'))
(OUT/'404.html').write_text(page('Page not found','<section class="project-hero"><h1>Page not found.</h1><p><a href="https://taylorparsons.github.io/">Return to the project catalog</a></p></section>'))
shutil.copytree(ROOT/'assets',OUT/'assets',dirs_exist_ok=True)
(OUT/'.nojekyll').touch()
print(f'Rendered {len(projects)} project guides and 4 site pages into {OUT}')
